name: Upload Release Asset

on:
  release:
    types: [published]

jobs:
  build:
    name: Build release zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: npm run build-plugin

      - name: Rename output file
        run: mv icepay-for-woocommerce.zip icepay-for-woocommerce-${{ github.ref_name }}.zip

      - name: Add to release
        uses: softprops/action-gh-release@v2
        with:
          files: icepay-for-woocommerce-${{ github.ref_name }}.zip
